version: '3.7'
services:
  php:
    container_name: eget_test
    build: .
    ports:
     - "8015:80"
     - "443:443"
    volumes:
     - ./:/var/www/html
    links:
     - mysql

  mysql:
    container_name: eget_test_db
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
     - MYSQL_PASSWORD=root
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=eget_test

volumes:
  dbdata: