version: '3.7'
services:
  php:
    container_name: eget_test
    build: .
    ports:
     - "8015:80"
     - "443:443"
    volumes:
     - ./:/var/www/html
    links:
     - db
     - db_testing

  db:
    container_name: eget_test_db
    image: postgres
    ports:
      - "54322:5432"
    volumes:
      - eget_test_pgsql_vol:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_USER=root
     - POSTGRES_DB=eget_test

  db_testing:
    container_name: eget_test_db_phpunit
    image: postgres
    ports:
      - "54323:5432"
    volumes:
      - eget_test_pgsql_testing_vol:/var/lib/postgresql/data
    environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_USER=root
     - POSTGRES_DB=eget_test_phpunit

volumes:
  eget_test_pgsql_vol:
  eget_test_pgsql_testing_vol: