version: '3.7'
services:
  php:
    container_name: eget_test
    build: .
    ports:
     - "8015:80"
     - "443:443"
    volumes:
     - ./:/var/www/html
    links:
     - db

  db:
    container_name: eget_test_db
    image: postgres
    ports:
      - "54322:5432"
    volumes:
      - dbdata:/var/lib/db
    environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_USER=root
     - POSTGRES_DB=eget_test

volumes:
  dbdata: